#!/bin/bash
git pull
cp -rf ~/github/wileycousins/* ~/webapps/wileycousins/
cp -rf ~/github/wileycousins/public/images/* ~/webapps/wileycousins_static/
cd ~/webapps/wileycousins/
npm install
source .env
forever stop $PWD/app.coffee
forever -a -l wileycousins.log start -c coffee $PWD/app.coffee &
#./bin/start
