#!/bin/bash
git pull
cp -rf ~/github/wileycousins/* ~/webapps/wileycousins/
cp -rf ~/github/wileycousins/public/images/* ~/webapps/wileycousins_static/
cd ~/webapps/wileycousins/
npm install
source .env
pm2 reload wileycousins
#./bin/start
